version: "3.7"

services:
  ai-backend-connector:
    build: .
    image: ai-backend-connector:1.0.0-ubuntu1804
    command: ["python3", "web_robot_backend.py"]
    container_name: ai-backend-connector
    network_mode: "host"
    ports:
      - 5200:5200/udp
      - 8080:8080
    volumes:
        - ./:/code
