ip_camera_params:
    video_url: "udp://@224.0.0.0:1234" #"http://192.168.43.1:8080/videofeed" # "udp://@224.0.0.0:1234" #"http://192.168.10.55:8080/videofeed"
    calibration_params_file: "camera_calibration/calib-params.json"
    cropped_video_size: 1080
    original_video_height: 1080
    original_video_width: 1080
    resize_video_size: 1080
    size_of_marker: 0.047 # Size in meters
    min_ball_area_to_detect: 50 # See ip_cam_connection.py _find_center_points-function to get the right value to this variable
    arena_size_in_meters: 4

    # Value ranges for HSV-values in OpenCV
    # H: 0-179, S: 0-255, V: 0-255
    low_pink_ball_color_hsv: [150, 130, 170]
    high_pink_ball_color_hsv: [173, 255, 255]
    low_yellow_ball_color_hsv: [25, 80, 124]
    high_yellow_ball_color_hsv: [42, 255, 255]

game_params:
    angles: [-100, -45, -20, 0, 20, 45, 100]
    ray_length: 5.657 # SQRY(4^2 + 4^2)
    robot_speed: 115 # 2.35 seconds / meter 
    turn_speed: 1 # Percent of robot_speed ## 2.6 seconds / full 360 degree turn
    arena_params_path: "arena_params/" # Path to folder with slash
    team_color: "red" # Either blue or red
    agent_params:
        striker:
            aruco_code: 28
        
        goalie:
            aruco_code: 29

unity_params:
    unity_ip: "127.0.0.1"
    unity_port: "50051"

robot_reporter:
    port: 5105