# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import RemoteImageToActions_pb2 as proto_dot_RemoteImageToActions__pb2


class ImageToActionsServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageToActions = channel.unary_unary(
                '/remoteimagetoactions.ImageToActionsServer/ImageToActions',
                request_serializer=proto_dot_RemoteImageToActions__pb2.ActionsRequest.SerializeToString,
                response_deserializer=proto_dot_RemoteImageToActions__pb2.ActionsResponse.FromString,
                )


class ImageToActionsServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageToActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageToActionsServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageToActions': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageToActions,
                    request_deserializer=proto_dot_RemoteImageToActions__pb2.ActionsRequest.FromString,
                    response_serializer=proto_dot_RemoteImageToActions__pb2.ActionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remoteimagetoactions.ImageToActionsServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageToActionsServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageToActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remoteimagetoactions.ImageToActionsServer/ImageToActions',
            proto_dot_RemoteImageToActions__pb2.ActionsRequest.SerializeToString,
            proto_dot_RemoteImageToActions__pb2.ActionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
