# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/RemoteImageToActions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/RemoteImageToActions.proto',
  package='remoteimagetoactions',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n proto/RemoteImageToActions.proto\x12\x14remoteimagetoactions\"\x1f\n\x0e\x41\x63tionsRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"4\n\x0bRobotAction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x12\x15\n\rarucoMarkerID\x18\x02 \x01(\x05\"T\n\x0f\x41\x63tionsResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x32\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32!.remoteimagetoactions.RobotAction2w\n\x14ImageToActionsServer\x12_\n\x0eImageToActions\x12$.remoteimagetoactions.ActionsRequest\x1a%.remoteimagetoactions.ActionsResponse\"\x00\x62\x06proto3'
)




_ACTIONSREQUEST = _descriptor.Descriptor(
  name='ActionsRequest',
  full_name='remoteimagetoactions.ActionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='remoteimagetoactions.ActionsRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=89,
)


_ROBOTACTION = _descriptor.Descriptor(
  name='RobotAction',
  full_name='remoteimagetoactions.RobotAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='remoteimagetoactions.RobotAction.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arucoMarkerID', full_name='remoteimagetoactions.RobotAction.arucoMarkerID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=143,
)


_ACTIONSRESPONSE = _descriptor.Descriptor(
  name='ActionsResponse',
  full_name='remoteimagetoactions.ActionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='remoteimagetoactions.ActionsResponse.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions', full_name='remoteimagetoactions.ActionsResponse.actions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=229,
)

_ACTIONSRESPONSE.fields_by_name['actions'].message_type = _ROBOTACTION
DESCRIPTOR.message_types_by_name['ActionsRequest'] = _ACTIONSREQUEST
DESCRIPTOR.message_types_by_name['RobotAction'] = _ROBOTACTION
DESCRIPTOR.message_types_by_name['ActionsResponse'] = _ACTIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionsRequest = _reflection.GeneratedProtocolMessageType('ActionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONSREQUEST,
  '__module__' : 'proto.RemoteImageToActions_pb2'
  # @@protoc_insertion_point(class_scope:remoteimagetoactions.ActionsRequest)
  })
_sym_db.RegisterMessage(ActionsRequest)

RobotAction = _reflection.GeneratedProtocolMessageType('RobotAction', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTACTION,
  '__module__' : 'proto.RemoteImageToActions_pb2'
  # @@protoc_insertion_point(class_scope:remoteimagetoactions.RobotAction)
  })
_sym_db.RegisterMessage(RobotAction)

ActionsResponse = _reflection.GeneratedProtocolMessageType('ActionsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONSRESPONSE,
  '__module__' : 'proto.RemoteImageToActions_pb2'
  # @@protoc_insertion_point(class_scope:remoteimagetoactions.ActionsResponse)
  })
_sym_db.RegisterMessage(ActionsResponse)



_IMAGETOACTIONSSERVER = _descriptor.ServiceDescriptor(
  name='ImageToActionsServer',
  full_name='remoteimagetoactions.ImageToActionsServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=231,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='ImageToActions',
    full_name='remoteimagetoactions.ImageToActionsServer.ImageToActions',
    index=0,
    containing_service=None,
    input_type=_ACTIONSREQUEST,
    output_type=_ACTIONSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGETOACTIONSSERVER)

DESCRIPTOR.services_by_name['ImageToActionsServer'] = _IMAGETOACTIONSSERVER

# @@protoc_insertion_point(module_scope)
