# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/RobotSystemCommunication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/RobotSystemCommunication.proto',
  package='robotsystemcommunication',
  syntax='proto3',
  serialized_pb=_b('\n$proto/RobotSystemCommunication.proto\x12\x18robotsystemcommunication\"G\n\x12RobotActionRequest\x12\x17\n\x0fleftMotorAction\x18\x01 \x01(\x05\x12\x18\n\x10rightMotorAction\x18\x02 \x01(\x05\"K\n\x13RobotActionResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.robotsystemcommunication.StatusType\"%\n\x13\x42rainActionResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\"J\n\x12\x42rainActionRequest\x12\x19\n\x11lowerObservations\x18\x01 \x03(\x02\x12\x19\n\x11upperObservations\x18\x02 \x03(\x02\"0\n\x1fSimulationScreenCaptureResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x8b\x01\n\x1eSimulationScreenCaptureRequest\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05widht\x18\x02 \x01(\x05\x12\x36\n\timageType\x18\x03 \x01(\x0e\x32#.robotsystemcommunication.ImageType\x12\x12\n\njpgQuality\x18\x04 \x01(\x05\")\n\x17SimulationActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\"P\n\x18SimulationActionResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.robotsystemcommunication.StatusType*\x1f\n\nStatusType\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01*\x1d\n\tImageType\x12\x07\n\x03JPG\x10\x00\x12\x07\n\x03PNG\x10\x01\x32|\n\rRobotFrontend\x12k\n\nMakeAction\x12,.robotsystemcommunication.RobotActionRequest\x1a-.robotsystemcommunication.RobotActionResponse\"\x00\x32y\n\x0b\x42rainServer\x12j\n\tGetAction\x12,.robotsystemcommunication.BrainActionRequest\x1a-.robotsystemcommunication.BrainActionResponse\"\x00\x32\x95\x02\n\x10SimulationServer\x12\x89\x01\n\x10GetScreenCapture\x12\x38.robotsystemcommunication.SimulationScreenCaptureRequest\x1a\x39.robotsystemcommunication.SimulationScreenCaptureResponse\"\x00\x12u\n\nMakeAction\x12\x31.robotsystemcommunication.SimulationActionRequest\x1a\x32.robotsystemcommunication.SimulationActionResponse\"\x00\x62\x06proto3')
)

_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='robotsystemcommunication.StatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=648,
  serialized_end=679,
)
_sym_db.RegisterEnumDescriptor(_STATUSTYPE)

StatusType = enum_type_wrapper.EnumTypeWrapper(_STATUSTYPE)
_IMAGETYPE = _descriptor.EnumDescriptor(
  name='ImageType',
  full_name='robotsystemcommunication.ImageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JPG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=681,
  serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_IMAGETYPE)

ImageType = enum_type_wrapper.EnumTypeWrapper(_IMAGETYPE)
OK = 0
ERROR = 1
JPG = 0
PNG = 1



_ROBOTACTIONREQUEST = _descriptor.Descriptor(
  name='RobotActionRequest',
  full_name='robotsystemcommunication.RobotActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leftMotorAction', full_name='robotsystemcommunication.RobotActionRequest.leftMotorAction', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightMotorAction', full_name='robotsystemcommunication.RobotActionRequest.rightMotorAction', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=137,
)


_ROBOTACTIONRESPONSE = _descriptor.Descriptor(
  name='RobotActionResponse',
  full_name='robotsystemcommunication.RobotActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='robotsystemcommunication.RobotActionResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=214,
)


_BRAINACTIONRESPONSE = _descriptor.Descriptor(
  name='BrainActionResponse',
  full_name='robotsystemcommunication.BrainActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='robotsystemcommunication.BrainActionResponse.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=253,
)


_BRAINACTIONREQUEST = _descriptor.Descriptor(
  name='BrainActionRequest',
  full_name='robotsystemcommunication.BrainActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lowerObservations', full_name='robotsystemcommunication.BrainActionRequest.lowerObservations', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upperObservations', full_name='robotsystemcommunication.BrainActionRequest.upperObservations', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=329,
)


_SIMULATIONSCREENCAPTURERESPONSE = _descriptor.Descriptor(
  name='SimulationScreenCaptureResponse',
  full_name='robotsystemcommunication.SimulationScreenCaptureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='robotsystemcommunication.SimulationScreenCaptureResponse.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=379,
)


_SIMULATIONSCREENCAPTUREREQUEST = _descriptor.Descriptor(
  name='SimulationScreenCaptureRequest',
  full_name='robotsystemcommunication.SimulationScreenCaptureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='robotsystemcommunication.SimulationScreenCaptureRequest.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='widht', full_name='robotsystemcommunication.SimulationScreenCaptureRequest.widht', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imageType', full_name='robotsystemcommunication.SimulationScreenCaptureRequest.imageType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jpgQuality', full_name='robotsystemcommunication.SimulationScreenCaptureRequest.jpgQuality', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=521,
)


_SIMULATIONACTIONREQUEST = _descriptor.Descriptor(
  name='SimulationActionRequest',
  full_name='robotsystemcommunication.SimulationActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='robotsystemcommunication.SimulationActionRequest.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=564,
)


_SIMULATIONACTIONRESPONSE = _descriptor.Descriptor(
  name='SimulationActionResponse',
  full_name='robotsystemcommunication.SimulationActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='robotsystemcommunication.SimulationActionResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=646,
)

_ROBOTACTIONRESPONSE.fields_by_name['status'].enum_type = _STATUSTYPE
_SIMULATIONSCREENCAPTUREREQUEST.fields_by_name['imageType'].enum_type = _IMAGETYPE
_SIMULATIONACTIONRESPONSE.fields_by_name['status'].enum_type = _STATUSTYPE
DESCRIPTOR.message_types_by_name['RobotActionRequest'] = _ROBOTACTIONREQUEST
DESCRIPTOR.message_types_by_name['RobotActionResponse'] = _ROBOTACTIONRESPONSE
DESCRIPTOR.message_types_by_name['BrainActionResponse'] = _BRAINACTIONRESPONSE
DESCRIPTOR.message_types_by_name['BrainActionRequest'] = _BRAINACTIONREQUEST
DESCRIPTOR.message_types_by_name['SimulationScreenCaptureResponse'] = _SIMULATIONSCREENCAPTURERESPONSE
DESCRIPTOR.message_types_by_name['SimulationScreenCaptureRequest'] = _SIMULATIONSCREENCAPTUREREQUEST
DESCRIPTOR.message_types_by_name['SimulationActionRequest'] = _SIMULATIONACTIONREQUEST
DESCRIPTOR.message_types_by_name['SimulationActionResponse'] = _SIMULATIONACTIONRESPONSE
DESCRIPTOR.enum_types_by_name['StatusType'] = _STATUSTYPE
DESCRIPTOR.enum_types_by_name['ImageType'] = _IMAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotActionRequest = _reflection.GeneratedProtocolMessageType('RobotActionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTACTIONREQUEST,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.RobotActionRequest)
  ))
_sym_db.RegisterMessage(RobotActionRequest)

RobotActionResponse = _reflection.GeneratedProtocolMessageType('RobotActionResponse', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTACTIONRESPONSE,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.RobotActionResponse)
  ))
_sym_db.RegisterMessage(RobotActionResponse)

BrainActionResponse = _reflection.GeneratedProtocolMessageType('BrainActionResponse', (_message.Message,), dict(
  DESCRIPTOR = _BRAINACTIONRESPONSE,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.BrainActionResponse)
  ))
_sym_db.RegisterMessage(BrainActionResponse)

BrainActionRequest = _reflection.GeneratedProtocolMessageType('BrainActionRequest', (_message.Message,), dict(
  DESCRIPTOR = _BRAINACTIONREQUEST,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.BrainActionRequest)
  ))
_sym_db.RegisterMessage(BrainActionRequest)

SimulationScreenCaptureResponse = _reflection.GeneratedProtocolMessageType('SimulationScreenCaptureResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONSCREENCAPTURERESPONSE,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.SimulationScreenCaptureResponse)
  ))
_sym_db.RegisterMessage(SimulationScreenCaptureResponse)

SimulationScreenCaptureRequest = _reflection.GeneratedProtocolMessageType('SimulationScreenCaptureRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONSCREENCAPTUREREQUEST,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.SimulationScreenCaptureRequest)
  ))
_sym_db.RegisterMessage(SimulationScreenCaptureRequest)

SimulationActionRequest = _reflection.GeneratedProtocolMessageType('SimulationActionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONACTIONREQUEST,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.SimulationActionRequest)
  ))
_sym_db.RegisterMessage(SimulationActionRequest)

SimulationActionResponse = _reflection.GeneratedProtocolMessageType('SimulationActionResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONACTIONRESPONSE,
  __module__ = 'proto.RobotSystemCommunication_pb2'
  # @@protoc_insertion_point(class_scope:robotsystemcommunication.SimulationActionResponse)
  ))
_sym_db.RegisterMessage(SimulationActionResponse)



_ROBOTFRONTEND = _descriptor.ServiceDescriptor(
  name='RobotFrontend',
  full_name='robotsystemcommunication.RobotFrontend',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=712,
  serialized_end=836,
  methods=[
  _descriptor.MethodDescriptor(
    name='MakeAction',
    full_name='robotsystemcommunication.RobotFrontend.MakeAction',
    index=0,
    containing_service=None,
    input_type=_ROBOTACTIONREQUEST,
    output_type=_ROBOTACTIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOTFRONTEND)

DESCRIPTOR.services_by_name['RobotFrontend'] = _ROBOTFRONTEND


_BRAINSERVER = _descriptor.ServiceDescriptor(
  name='BrainServer',
  full_name='robotsystemcommunication.BrainServer',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=838,
  serialized_end=959,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAction',
    full_name='robotsystemcommunication.BrainServer.GetAction',
    index=0,
    containing_service=None,
    input_type=_BRAINACTIONREQUEST,
    output_type=_BRAINACTIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BRAINSERVER)

DESCRIPTOR.services_by_name['BrainServer'] = _BRAINSERVER


_SIMULATIONSERVER = _descriptor.ServiceDescriptor(
  name='SimulationServer',
  full_name='robotsystemcommunication.SimulationServer',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=962,
  serialized_end=1239,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetScreenCapture',
    full_name='robotsystemcommunication.SimulationServer.GetScreenCapture',
    index=0,
    containing_service=None,
    input_type=_SIMULATIONSCREENCAPTUREREQUEST,
    output_type=_SIMULATIONSCREENCAPTURERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MakeAction',
    full_name='robotsystemcommunication.SimulationServer.MakeAction',
    index=1,
    containing_service=None,
    input_type=_SIMULATIONACTIONREQUEST,
    output_type=_SIMULATIONACTIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMULATIONSERVER)

DESCRIPTOR.services_by_name['SimulationServer'] = _SIMULATIONSERVER

# @@protoc_insertion_point(module_scope)
